### ISSUE TITLE
历史使用者宣传展示

### ISSUE THREAD

**Issue by Peatsuki** [ShigemoriHakura/aclivechat#10]
根据使用记录，展示弹幕姬历史使用者，详见隔壁。
一个令人激动又快乐的issue！！

**Comment by Sokwva** [comment]
我觉得不是很好

**Comment by ShigemoriHakura** [comment]
可能会加页面把当前连接的用户直播间ID展示出来，但是数据上传什么的不打算做。
讲道理a站现在也就这一个弹幕姬能自定义balabala啊。。。（
