### ISSUE TITLE
websocket链接意外关闭

### ISSUE THREAD

**Issue by wpscott** [ShigemoriHakura/aclivechat#11]
测试的时候发现websocket链接会意外关闭，用[Data Race Detector](https://golang.org/doc/articles/race_detector.html)测试发现有几个data race bug
<img width="547" alt="data race 1" src="https://user-images.githubusercontent.com/6392170/94834993-17fd5200-03df-11eb-8b32-89f3976f7247.png">
<img width="549" alt="data race 2" src="https://user-images.githubusercontent.com/6392170/94834995-1895e880-03df-11eb-8aa3-8d4942cd435b.png">

**Comment by ShigemoriHakura** [comment]
https://github.com/ShigemoriHakura/aclivechat/commit/0bd18ec3e0ad24118bff04bde99bbc417f3bf9df
测一下这个commit

**Comment by orzogc** [comment]
68795f14777ce0baa3c02b0ed165ce110675c5ee 应该已经修复data race的问题
websocket连接意外关闭是指弹幕库那边还是弹幕姬的前后端通讯？

**Comment by wpscott** [comment]
我正在写的OBS插件连接弹幕姬的时候
<img width="405" alt="data race 3" src="https://user-images.githubusercontent.com/6392170/94935266-d500b480-049a-11eb-8dde-4e4d6b66784d.png">

这是用网页打开弹幕姬的时候
<img width="429" alt="data race 4" src="https://user-images.githubusercontent.com/6392170/94935208-bef2f400-049a-11eb-867c-1e50871ff2bb.png">
<img width="420" alt="data race 5" src="https://user-images.githubusercontent.com/6392170/94935211-bf8b8a80-049a-11eb-8a2d-bf25d275d721.png">

**Comment by ShigemoriHakura** [comment]
正常，设计是：前端发送第一个带roomId的请求后，之后的连接会被直接关闭，后端处理房间连接完成后，前端的请求才会被接受。

**Comment by ShigemoriHakura** [comment]
cmd：0是前端发的心跳包

**Comment by wpscott** [comment]
不能保持一个连接吗？

**Comment by ShigemoriHakura** [comment]
你不打算做自动重连机制么。。。

**Comment by ShigemoriHakura** [comment]
因为前端有自动重连 所以我就偷懒直接close了=-=

**Comment by wpscott** [comment]
本地连接也会丢失吗？我不打算做远程连接

**Comment by ShigemoriHakura** [comment]
最好还是设计个自动重连机制吧，不然万一后端出什么bug崩溃，重新启动后端以后你没有重连机制就很尴尬了

**Comment by wpscott** [comment]
好吧

**Comment by ShigemoriHakura** [comment]
我go这边并不是很常用，不能保证完全不出bug的。。。（（（

**Comment by orzogc** [comment]
时间不急的话我可以写个通用后端，不知道你对后端有什么要求？

**Comment by wpscott** [comment]
先说一下我的摸鱼计划吧
- [x] 礼物掉落（基本完成）
- [ ] 关注动画？（可能考虑统计反复关注的次数）
- [ ] 礼物榜，可能考虑在本地建立数据库，方便统计
- [ ] 心愿单（如关注数、观众数、点赞数或特定的礼物数等）
- [ ] 自动黑名单踢人，比如在Github上创建一个直播观众黑名单的repository，由commit或pr添加及删除uid及理由，根据名单自动踢人。

**Comment by ShigemoriHakura** [comment]
礼物掉落还是做在面捕软件里面比较实在
关注动画啊礼物榜啊心愿单啊什么的可以直接改隔壁的现成插件
黑名单踢人涉及到一些操作api了，看猴子给不给用吧

**Comment by Sokwva** [comment]
> 先说一下我的摸鱼计划吧
> 
> * [x]  礼物掉落（基本完成）
> * [ ]  关注动画？（可能考虑统计反复关注的次数）
> * [ ]  礼物榜，可能考虑在本地建立数据库，方便统计
> * [ ]  心愿单（如关注数、观众数、点赞数或特定的礼物数等）
> * [ ]  自动黑名单踢人，比如在Github上创建一个直播观众黑名单的repository，由commit或pr添加及删除uid及理由，根据名单自动踢人。

但是感觉使用github对v来说可能有点门槛

**Comment by Sokwva** [comment]
> 礼物掉落还是做在面捕软件里面比较实在
> 关注动画啊礼物榜啊心愿单啊什么的可以直接改隔壁的现成插件
> 黑名单踢人涉及到一些操作api了，看猴子给不给用吧

就单独一套数据吧

**Comment by wpscott** [comment]
> 礼物掉落还是做在面捕软件里面比较实在
> 关注动画啊礼物榜啊心愿单啊什么的可以直接改隔壁的现成插件
> 黑名单踢人涉及到一些操作api了，看猴子给不给用吧

我的摸鱼计划的意思是在摸鱼的时候重新打造一套轮子，而不是改现有的轮子

**Comment by wpscott** [comment]
> > 先说一下我的摸鱼计划吧
> > 
> > * [x]   礼物掉落（基本完成）
> > * [ ]   关注动画？（可能考虑统计反复关注的次数）
> > * [ ]   礼物榜，可能考虑在本地建立数据库，方便统计
> > * [ ]   心愿单（如关注数、观众数、点赞数或特定的礼物数等）
> > * [ ]   自动黑名单踢人，比如在Github上创建一个直播观众黑名单的repository，由commit或pr添加及删除uid及理由，根据名单自动踢人。
> 
> 但是感觉使用github对v来说可能有点门槛

是说黑名单吗，使用的时候对GitHub是无感的。请求添加或删除的话也可以开issue或者请人帮忙。
