### ISSUE TITLE
特别关注用户

### ISSUE THREAD

**Issue by Sokwva** [ShigemoriHakura/aclivechat#3]
能否加入特别关注用户标记（标记用户房间加入、用户发言、用户送礼等相关事件），以便在弹幕显示区域以不同的样式展现出来

**Comment by ShigemoriHakura** [comment]
我前端不行 主要是你想怎么展示 单独颜色？
主要尽量要保证css的兼容性比较好

**Comment by Sokwva** [comment]
我觉得就在头像前面加一个星号之类的应该就差不多了

**Comment by ShigemoriHakura** [comment]
作为用户标记显示功能合并
